name: Build and Package

on:
  push:
    branches:
      - main # 或者你的目标分支

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.9' 

    - name: Create Virtual Environment and Install Dependencies
      run: |
        python -m venv jntpy-gui-env
        .\jntpy-gui-env\Scripts\activate
        pip install -r requirements.txt

    - name: Package Python script
      run: |
        pyinstaller -F --noconsole script.py
        move dist\script.exe script.exe

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.20.0' 

    - name: Install npm dependencies
      run: npm install

    - name: Build Electron app
      run: npm run dist
